### ISSUE TITLE
Using splash with docker compose

### ISSUE THREAD

**Issue by fyquah** [scrapy-plugins/scrapy-splash#90]
I am using docker splash with the docker compose configuration as such:

```
scrapy:
    build:
      context: .
      dockerfile: Dockerfile.scrapy
    volumes:
    - .:/app
    environment:
      PYTHONPATH: "/app"
      SPLASH_URL: "http://splash:8050"
    depends_on:
    - splash
  splash:
    image: scrapinghub/splash
    ports:
    - "8050:8050"
```

However, on running `docker-compose -f docker-compose.yml up scrapy`, I obtain the following error:

```
scrapy_1    | 2016-11-01 06:10:45 [scrapy] INFO: Enabled item pipelines:
scrapy_1    | []
scrapy_1    | 2016-11-01 06:10:45 [scrapy] INFO: Spider opened
scrapy_1    | 2016-11-01 06:10:45 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
scrapy_1    | 2016-11-01 06:10:45 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
scrapy_1    | 2016-11-01 06:10:46 [scrapy] DEBUG: Retrying <POST http://splash:8050/render.html> (failed 1 times): 502 Bad Gateway
scrapy_1    | 2016-11-01 06:10:46 [scrapy] DEBUG: Retrying <POST http://splash:8050/render.html> (failed 2 times): 502 Bad Gateway
scrapy_1    | 2016-11-01 06:10:46 [scrapy] DEBUG: Gave up retrying <POST http://splash:8050/render.html> (failed 3 times): 502 Bad Gateway
scrapy_1    | 2016-11-01 06:10:46 [scrapy] DEBUG: Crawled (502) <POST http://splash:8050/render.html> (referer: None)
scrapy_1    | 2016-11-01 06:10:46 [scrapy] DEBUG: Ignoring response <502 http://splash:8050/render.html>: HTTP status code is not handled or not allowed
scrapy_1    | 2016-11-01 06:10:46 [scrapy] INFO: Closing spider (finished)
scrapy_1    | 2016-11-01 06:10:46 [scrapy] INFO: Dumping Scrapy stats:
```

Am I missing something here? `0.0.0.0:8050` works fine on my local machine.
